//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorProductoBack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardarT
    {
        public int IdTransaccion { get; set; }
        public string IdProducto { get; set; }
        public Nullable<int> CantidadProducto { get; set; }
        public string FechachaTransaccion { get; set; }
        public string IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoUsuario { get; set; }
        public string IdBodegaOrigen { get; set; }
        public string IdBodegaDestino { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
