//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorProductoBack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardarM
    {
        public string IdModificar { get; set; }
        public string FechaModificacion { get; set; }
        public string IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public string AccionModificacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
