//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorProductoBack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.GuardarT = new HashSet<GuardarT>();
        }
    
        public string IdProducto { get; set; }
        public string IdBodega { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public Nullable<decimal> CostoProducto { get; set; }
        public Nullable<decimal> PrecioVentaProducto { get; set; }
        public Nullable<int> StockProducto { get; set; }
        public string CategoriaProducto { get; set; }
        public string IdUsuario { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuardarT> GuardarT { get; set; }
    }
}
